//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMANTENIMIENTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRUEBA
    {
        public int IDALUMNO { get; set; }
        public string ALUMNO { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
    }
}
